#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"
#include "images/jacket_invaders.h"
#include "images/background.h"
#include "images/black_alien.h"
#include "images/yellow_jacket.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.

//prototypes
void drawLost(void);
void drawWon(void);

struct state cs;
struct player player;
struct player oldPlayer;
struct alien aliens;

int main(void) {
  /* TODO: */
  // Manipulate REGt_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;


  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  char timerTxt[51];

  // Load initial application state
  cs.gba_state = START;
  aliens.row = 10;
  aliens.col = 10;
  aliens.height = 30;
  aliens.width = 30;
  player.row = 80;
  player.col = 120; 
  player.height = 21;
  player.width = 30;

  player.timer = 0;


  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons

    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw
    waitForVBlank();
    switch (cs.gba_state) {
      case START:
        drawFullScreenImageDMA(jacket_invaders);
        cs.gba_state = START_BUFFER;
        break;
      case START_BUFFER: 
        if (KEY_JUST_PRESSED(BUTTON_START, currentButtons, previousButtons)) {
          clock = 0;
          player.row = 120;
          player.col = 200; 
          cs.gba_state = INITPLAY;
        }
        break;
      case INITPLAY:
        fillScreenDMA(BLACK);
        drawImageDMA(player.row, player.col, player.width, player.height, yellow_jacket);
        drawImageDMA(aliens.col, aliens.row, aliens.width, aliens.height, black_alien);
        cs.gba_state = PLAY;
        break;
      case PLAY:
        player.timer = 6 - (clock / 60);
        oldPlayer = player;

        if(aliens.col > (player.row - aliens.width) && aliens.col < (player.row + YELLOW_JACKET_WIDTH)) {
          if(aliens.row > (player.col - aliens.height) && aliens.row < (player.col + YELLOW_JACKET_HEIGHT)) {
              cs.gba_state = WIN;
          }
        }
        if(KEY_DOWN(BUTTON_LEFT, currentButtons)) {
          if(player.col > 0) {
            player.col--;
          }
        }
        if(KEY_DOWN(BUTTON_RIGHT, currentButtons)) {
          if(player.col < WIDTH - YELLOW_JACKET_WIDTH) {
            player.col++;
          }
        }
        if(KEY_DOWN(BUTTON_UP, currentButtons)) {
          if(player.row > 0) {
            player.row--;
          }
        }
        if(KEY_DOWN(BUTTON_DOWN, currentButtons)) {
          if(player.row < 160 - YELLOW_JACKET_HEIGHT) {
            player.row++;
          }
        }

        drawRectDMA(150, 10, 100, 10, BLACK);
        drawRectDMA(oldPlayer.row, oldPlayer.col, oldPlayer.width, oldPlayer.height, BLACK);
        
        drawImageDMA(player.row, player.col, player.width, player.height, yellow_jacket);
        drawImageDMA(aliens.col, aliens.row, aliens.width, aliens.height, black_alien);

        sprintf(timerTxt, "TIMER: %d", player.timer);
        drawString(150, 15, timerTxt, WHITE);

        if(KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          cs.gba_state = START;
        }
        if (player.timer == 0) {
          drawLost();
          cs.gba_state = LOSE;
        }
        break;
      case WIN:
        drawWon();
        if (KEY_JUST_PRESSED(BUTTON_SELECT, currentButtons, previousButtons)) {
          cs.gba_state = START;
        }
        break;
      case LOSE:
        drawLost();
        if (KEY_DOWN(BUTTON_SELECT, currentButtons)) {
          cs.gba_state = START;
        }
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}

void drawLost(void) {
  fillScreenDMA(RED);
  drawString(70, 90, "GAME OVER!", WHITE);
  cs.gba_state = LOSE;
}

void drawWon(void) {
  fillScreenDMA(YELLOW);
  drawString(70, 45, "CONGRATS JACKET, YOU WON!", BLACK);
  cs.gba_state = WIN;
}
